version: "3"
services:
  # tomcat:
  #   image: tomcat:9.0
  #   ports: 
  #     - "8080:8080"
  #   volumes:
  #     - "./webapps:/usr/local/tomcat/webapps"
  mysql:
    image: mysql
    volumes:
      - ./mysqlData:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3307:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - UPLOAD_LIMIT=300M
    # restart: always
    ports:
      - 8081:80